---
title: "Monte Carlo Simulation"
author: "Kiran Kumar Patro"
date: "August 30, 2017"
output: html_document
---

#Monte Carlo Simulation



```{r}
samedayornot= function(numSims) {
  sameday=0
  notsameday =0
  set.seed(1244)
  for (i in 1:numSims) {
    
    date.seq <- seq(as.Date('1950/01/01'), as.Date('2017/01/01'), by="day") 
    
    date1 <- sample(date.seq,1)
    date2 <- sample(date.seq,1)
```

# find the week days to the two randomly generated dates


```{r}
weekday1 <-weekdays(as.Date(date1))
    weekday2<- weekdays(as.Date(date2))

weekday1 =    as.character(weekday1)
weekday2 =    as.character(weekday2)
```


# check whether weekday of the two different dates

```{r}
if (weekday1 == weekday2){
      sameday =sameday+1
    } else{
      notsameday=notsameday+1
    }
    

    }
    
```


#probability of same day

```{r}
prob_sameday = sameday/(sameday+notsameday)
  
  return(prob_sameday)
 
  }
  
  




simulations=c(10,100,1000,10000,50000,100000)
par(mfrow=c(1,3))
start = Sys.time()
for (i in simulations) {
  prob=samedayornot(i)
  
  prob
  
 
}
prob
end=Sys.time()-start
end

start1 = Sys.time()
prob1 = sapply(simulations,samedayornot)
end1=Sys.time()-start1
end1

start2 = Sys.time()
prob2 = lapply(simulations,samedayornot)
end2=Sys.time()-start2
end2


```










